#!/usr/bin/env node
/**
 * Generate THIRD_PARTY_NOTICES.md from the licences actually installed.
 *
 * The wheel ships the built frontend, which means it redistributes six
 * JetBrains Mono font files and the runtime JS libraries compiled into the
 * bundle. The SIL Open Font License has an explicit notice condition and MIT
 * requires the copyright notice to travel with the copy — neither is satisfied
 * by the project's own LICENSE alone.
 *
 * Generated rather than hand-written so it cannot drift from package.json, and
 * committed rather than built on the fly so it is greppable in the repo and can
 * be verified in CI (`npm run notices:check`).
 *
 * Scope is `dependencies`, not `devDependencies`: only the former end up in
 * dist/. Vite, TypeScript and friends build the bundle without being in it.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const frontend = resolve(here, '..')
const repoRoot = resolve(frontend, '..')
const OUT = resolve(repoRoot, 'THIRD_PARTY_NOTICES.md')

const pkg = JSON.parse(readFileSync(resolve(frontend, 'package.json'), 'utf8'))
const names = Object.keys(pkg.dependencies ?? {}).sort()

function licenceFileFor(name) {
  const dir = resolve(frontend, 'node_modules', name)
  const hit = readdirSync(dir).find((f) => /^licen[cs]e(\.|$)/i.test(f))
  if (!hit) throw new Error(`${name}: no LICENSE file — cannot satisfy its notice condition`)
  return readFileSync(resolve(dir, hit), 'utf8').trim()
}

const entries = names.map((name) => {
  const meta = JSON.parse(readFileSync(resolve(frontend, 'node_modules', name, 'package.json'), 'utf8'))
  return {
    name,
    version: meta.version,
    licence: meta.license ?? 'UNKNOWN',
    homepage: meta.homepage ?? meta.repository?.url ?? '',
    text: licenceFileFor(name),
  }
})

const unknown = entries.filter((e) => e.licence === 'UNKNOWN')
if (unknown.length) {
  throw new Error(`no SPDX licence declared for: ${unknown.map((e) => e.name).join(', ')}`)
}

const body = [
  '# Third-party notices',
  '',
  'Lamplighter itself is MIT licensed (see `LICENSE`). The distributed wheel and',
  'sdist also contain the built frontend, which embeds the following third-party',
  'work. Their licences and copyright notices are reproduced here in full, as',
  'those licences require.',
  '',
  '_Generated by `npm run notices` — edit that script, not this file._',
  '',
  '| Package | Version | Licence |',
  '| --- | --- | --- |',
  ...entries.map((e) => `| [${e.name}](${e.homepage}) | ${e.version} | ${e.licence} |`),
  '',
  ...entries.flatMap((e) => [
    '---',
    '',
    `## ${e.name} ${e.version}`,
    '',
    e.homepage ? `<${e.homepage}>` : '',
    '',
    '```',
    e.text,
    '```',
    '',
  ]),
].join('\n')

const previous = (() => {
  try {
    return readFileSync(OUT, 'utf8')
  } catch {
    return null
  }
})()

if (process.argv.includes('--check')) {
  if (previous !== body) {
    console.error(
      'THIRD_PARTY_NOTICES.md is out of date with frontend/package.json.\n' +
        'Run `npm run notices` in frontend/ and commit the result.'
    )
    process.exit(1)
  }
  console.log(`ok: THIRD_PARTY_NOTICES.md covers ${entries.length} packages`)
} else {
  writeFileSync(OUT, body)
  console.log(`wrote THIRD_PARTY_NOTICES.md — ${entries.length} packages`)
}
